# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yu-Lun (Larry) Tsai
author: Yu-Lun Tsai
email: yulunt@andrew.cmu.edu
# Permalinks
permalink:        "/blog/:month-:day-:year/:title.html"

description: > # this means to ignore newlines until "baseurl:"
  Work hard, stay positive, and get up early. It's the best part of the day.
baseurl:          "/"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: stormysun513
github_username:  stormysun513

# Build settings
markdown: kramdown

github: https://github.com/stormysun513
linkedin: https://www.linkedin.com/in/yuluntsai
